<a href="https://colab.research.google.com/github/naomori/codexa_Pandas_Introduction/blob/master/Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question.1

In [0]:
import numpy as np
import pandas as pd

In [2]:
random = np.random.randint(0, 100, (5,5))
print(random)
df = pd.DataFrame(random)
df.shape

[[56 21 28 69 34]
 [33 62 97  5  4]
 [98 49 95  5 52]
 [55 33 34 14 35]
 [26 22 42 39  5]]


(5, 5)

answer: (5,5)

# Question.2

In [12]:
random = np.random.randint(0, 100, (3,3))
df = pd.DataFrame(random)

print(df)
df[2]

    0   1   2
0  16  61  79
1  66  62  20
2  75  59  46


0    79
1    20
2    46
Name: 2, dtype: int64

answer: A

# Question.3

In [14]:
df = pd.DataFrame(np.random.randn(4,4))
print(df)

          0         1         2         3
0  0.645970 -0.056748  0.383005 -2.012013
1  0.292343 -0.207021 -0.408709  1.224984
2 -1.058769 -0.349021 -0.665479  0.577795
3 -1.192558  0.756328  0.664285  0.576422


In [15]:
df.loc[:, 1]

0   -0.056748
1   -0.207021
2   -0.349021
3    0.756328
Name: 1, dtype: float64

answer: A

# Question.4

In [16]:
df = pd.DataFrame(np.random.randint(1, 50, (5,5)))
print(df)

    0   1   2   3   4
0  37  46  13  14  19
1  41  32  32  31  17
2  28  15  41  18  39
3   1  35  42  44  45
4  44  45  28  29  37


In [17]:
df.iloc[0:2, 4]

0    19
1    17
Name: 4, dtype: int64

answer: D

# Question.5

In [20]:
data = [[5, 37.0, 18.0, 4, 34],
       [44, 9.0, 8.0, 25, 17],
       [35, 45.0, np.nan, 11, 44],
       [23, 7.0, 3.0, 31, 20],
       [46, np.nan, np.nan, 17, 36]]
df = pd.DataFrame(data=data)
print(df)

    0     1     2   3   4
0   5  37.0  18.0   4  34
1  44   9.0   8.0  25  17
2  35  45.0   NaN  11  44
3  23   7.0   3.0  31  20
4  46   NaN   NaN  17  36


In [21]:
print(df.isnull())

       0      1      2      3      4
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False   True  False  False
3  False  False  False  False  False
4  False   True   True  False  False


In [22]:
print(df.isnull().sum())

0    0
1    1
2    2
3    0
4    0
dtype: int64


answer: 

# Question.6

In [23]:
columns=['Class', 'Sex']
index=['Satoshi', 'Ken', 'Jun', 'Tetsu', 'Yoshi']
data=[['1-1', 'Male'],
      ['1-5', 'Male'], 
      ['1-1', 'Male'],
      ['1-2', 'Male'],
      ['1-4', 'Male']]
user = pd.DataFrame(data=data, index=index, columns=columns)
print(user)

        Class   Sex
Satoshi   1-1  Male
Ken       1-5  Male
Jun       1-1  Male
Tetsu     1-2  Male
Yoshi     1-4  Male


In [25]:
columns=['Math', 'English', 'Chemistry', 'Physics', 'Music', 'id']
data=[[1, 22, 39, 38, 36, 'AB'],
      [13, 9, 44, 47, 40, 'AC'],
      [21, 21, 43, 22, 48, 'DE'],
      [28, 17, 19, 6, 32, 'ED'],
      [28, 32, 34, 20, 37, 'ER']]
kimatsu = pd.DataFrame(data=data, index=index, columns=columns)
print(kimatsu)

         Math  English  Chemistry  Physics  Music  id
Satoshi     1       22         39       38     36  AB
Ken        13        9         44       47     40  AC
Jun        21       21         43       22     48  DE
Tetsu      28       17         19        6     32  ED
Yoshi      28       32         34       20     37  ER


In [0]:
student = pd.merge(kimatsu, user, right_index=True, left_index=True)

In [27]:
print(student)

         Math  English  Chemistry  Physics  Music  id Class   Sex
Satoshi     1       22         39       38     36  AB   1-1  Male
Ken        13        9         44       47     40  AC   1-5  Male
Jun        21       21         43       22     48  DE   1-1  Male
Tetsu      28       17         19        6     32  ED   1-2  Male
Yoshi      28       32         34       20     37  ER   1-4  Male


In [0]:
student = kimatsu.join(user)

In [29]:
print(student)

         Math  English  Chemistry  Physics  Music  id Class   Sex
Satoshi     1       22         39       38     36  AB   1-1  Male
Ken        13        9         44       47     40  AC   1-5  Male
Jun        21       21         43       22     48  DE   1-1  Male
Tetsu      28       17         19        6     32  ED   1-2  Male
Yoshi      28       32         34       20     37  ER   1-4  Male


answer: E